# Generated by Django 5.2.1 on 2025-06-10 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0003_estudiante_padrefamilia_estudiantepadre_persona_and_more'),
        ('estructura_academica', '0001_initial'),
        ('inscripcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('tardanza', 'Tardanza'), ('justificado', 'Justificado')], max_length=20)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('bimestre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estructura_academica.bimestre')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inscripcion.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authapp.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inscripcion.materia')),
            ],
            options={
                'db_table': 'asistencia',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('bimestre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estructura_academica.bimestre')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inscripcion.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authapp.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inscripcion.materia')),
            ],
            options={
                'db_table': 'calificacion',
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bimestre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estructura_academica.bimestre')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inscripcion.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authapp.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inscripcion.materia')),
            ],
            options={
                'db_table': 'participacion',
            },
        ),
    ]
