# Generated by Django 5.2.1 on 2025-05-24 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'managed': True},
        ),
    ]
