# Generated by Django 5.2.1 on 2025-06-10 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0003_estudiante_padrefamilia_estudiantepadre_persona_and_more'),
        ('estructura_academica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_predicho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('probabilidad_riesgo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('bimestre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estructura_academica.bimestre')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authapp.estudiante')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estructura_academica.gestionacademica')),
            ],
            options={
                'db_table': 'prediccion_ml',
            },
        ),
        migrations.CreateModel(
            name='RecomendacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recomendaciones', models.JSONField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('bimestre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estructura_academica.bimestre')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authapp.estudiante')),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='estructura_academica.gestionacademica')),
            ],
            options={
                'db_table': 'recomendaciones_ia',
            },
        ),
    ]
